# Exported from Render on 2026-05-31T17:06:53Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Rebur
      runtime: node
      repo: https://github.com/jabarmcaffry/Rebur
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      region: oregon
      buildCommand: npm install
      startCommand: npm run start
      autoDeployTrigger: "off"
